#!/bin/bash

# handle the fact that this file will be used with multiple OSs
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  alias a='ls -lrth --color'
elif [[ $platform == 'Darwin' ]]; then
  alias a='ls -lrthG'
fi

#-- SYSTEM --#

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'


#-- ZSH --#
alias d='dirs -v'
alias cat='bat'
# for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack


#-- Neovim --#

alias v='nvim .'
alias vi='nvim'
alias vim='nvim'
alias svim='sudoedit'
alias nvimn='nvim --noplugin -u NONE'             # launch nvim without any plugin or config
alias editvim='vim ~/.config/nvim'


#-- GIT --#

alias lg='lazygit'
alias log="git log"
alias gg='git lg'
alias amend="git commit --amend"
alias review="git diff main"
alias patch='git format-patch HEAD^ --stdout > patch.diff'
alias prpush='git push -u origin HEAD'
alias squash='git rebase -i main'

alias g='git status'
alias ga='git add'
alias gad='git add --all .'
alias gc='git commit'
alias gcm="git commit -m"
alias gcl='git clone'
alias gpl='git pull'
alias gplo='git pull origin'
alias gpr='git pull --rebase'
alias grc='git rebase --continue'
alias gpo='git push origin'
alias gb='git branch '
alias gd='git diff'
alias gco='git checkout'
alias gr='git remote'
alias grs='git remote show'
alias gp='git push'
alias gpf='git push -f'
alias flog='fglog'
alias stash='git stash'
alias pop='git stash pop'

function fn_reset_branch() {
    branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
    git fetch && git reset --hard $branch
}

alias reset-branch="fn_reset_branch"

#-- TMUX --#

alias newscreen="tmux"
alias tmuxa='tmux attach -t'
alias tmuxn='tmux new-session -s'
alias tmuxk='tmux kill-session -t'
alias tmuxl='tmux list-sessions'


#-- DOCKER --#

alias docki="docker inspect"                                                    # display the information about a container
alias docke='docker exec -t -i'                                                 # going inside a container
alias dockDE='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
alias dockls='docker ps'                                                        # list docker containers
alias dockimg='docker images'                                                   # list images installed
alias dockprune='docker system prune -a'                                        # prune everything
alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
alias dockce='docker-compose run --rm'
alias kalidocker='docker run -t -i kalilinux/kali-linux-docker /bin/bash'

function fn_docker_stop() {
    id=$(docker container ls | fzf | awk '{print $1;}')
    docker stop $id
}

alias dockstop="fn_docker_stop"

#-- EXTRA --#

alias cl='clear && l'
alias ack='ag'
alias aliases="nvim $DOTFILES/zsh/aliases"
alias dotfiles="cd $DOTFILES"
alias search="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs nvim"

alias lls="exa -l -g --icons --git"
alias llt="exa -1 --icons --tree --git-ignore"

alias code="cd $HOME/Documents/projects && clear"
alias work="cd $HOME/Developer/Work && clear"
alias tutos="cd $HOME/Developer/Tutos && clear"

alias fs='foreman start'
alias rc='bin/rails console'
alias rs='bundle install && rails server'
alias rdm="bin/rake db:migrate"
alias killrudy='killall -9 ruby'
alias dropseed='bundle exec rake db:drop db:create db:migrate && bundle exec rake db:seed'
alias remigrate='rake db:migrate && rake db:migrate:redo && rake db:schema:dump && rake db:test:prepare'
alias rtest='bundle exec rspec --format documentation'

alias herokupush='git push heroku'
alias herokulogs='heroku logs -t'
alias staging-console='heroku run console --remote staging'
alias staging-tail='heroku logs --tail --remote staging'
alias production-console='heroku run console --remote production'
alias production-tail='heroku logs --tail --remote production'

alias restart_apache="sudo /etc/init.d/apache2 restart"
alias restart_postgres="stoppostgres && startpostgres"

alias startredis='redis-server /usr/local/etc/redis.conf &'
alias startpostgres='pg_ctl -D /usr/local/var/postgresql -l /usr/local/var/postgresql/server.log start'
alias stoppostgres='pg_ctl -D /usr/local/var/postgresql -l /usr/local/var/postgresql/server.log stop'
alias startelasticsearch='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'

alias nombom='npm cache clear && rm -rf node_modules && npm install'
alias weather='curl http://wttr\.in/CABA,argentina'

function work-on-issue() {
    issue=$(gh issue list | fzf --header "PLEASE SELECT AN ISSUE TO WORK ON" | awk -F '\t' '{ print $1 }')
    sanitized=$(gh issue view $issue --json "title" | jq -r ".title" | tr '[:upper:]' '[:lower:]' | tr -s -c "a-z0-9\n" "-" | head -c 60)
    branchname=$issue-$sanitized
    shortname=$(echo $branchname | head -c 30)
    if [[ ! -z "$shortname" ]]; then
        git fetch
        existing=$(git branch -a | grep -v remotes | grep $shortname | head -n 1)
        if [[ ! -z "$existing" ]]; then
            sh -c "git switch $existing"
        else
            bold=$(tput bold)
            normal=$(tput sgr0)
            echo "${bold}Please confirm new branch name:${normal}"
            vared branchname
            base=$(git branch --show-current)
            echo "${bold}Please confirm the base branch:${normal}"
            vared base
            git checkout -b $branchname origin/$base
            git push --set-upstream origin $branchname
        fi
    fi
}
